jewelryshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('store.urls', 'store'), namespace='store')),
]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import RegistrationView
from django.contrib.auth.views import LogoutView
from store import views as store_views

app_name = 'store'

urlpatterns = [
    # Main pages
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('shop/', views.shop_view, name='shop'),  # 🛠 Changed name to 'shop' for clarity

    # Cart & Orders
    path('cart/', views.cart, name='cart'),
    path('add-to-cart/<int:prod_id>/', views.add_to_cart, name='add-to-cart'),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name='remove-cart'),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name='plus-cart'),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name='minus-cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('checkout/<int:id>/', views.shop_checkout, name='shop_checkout'),
    path('place-order/', views.place_order, name='place-order'),
    path('success/', views.success, name='success'),
    path('payment-success/', views.payment_success, name='payment-success'),
    path('orders/', views.orders, name='orders'),
    path('order-history/', views.order_history, name='order_history'),
    path('download-invoice/<int:order_id>/', views.download_invoice, name='download_invoice'),



    # User Profile
    path('profile/', views.profile, name='profile'),
    path('update-profile-picture/', views.update_profile_picture, name='update_profile_picture'),


    # Categories & Products
    path('categories/', views.all_categories, name='categories'),
    path('category/<slug:slug>/', views.category_products, name='category-products'),
    path('product/<slug:slug>/', views.product_detail, name='product-detail'),
     

    # Blog
    path('blog/', views.blog_list, name='blog-list'),
    path('blog/<int:id>/', views.blog_post_detail, name='blog_post_detail'),

    # Address
    path('address/', views.AddressView.as_view(), name='add-address'),
    path('remove-address/<int:id>/', views.remove_address, name='remove-address'),

    # Auth
    path('register/', RegistrationView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),  # Add this line
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),

    # Password Reset
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='account/password_reset.html'),
         name='password-reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),

    # Optional
    path('order-success/', views.order_success, name='order-success'),
    path('test/', views.test, name='test'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block metatitle %}Jewelry Shop| Django Ecommerce{% endblock metatitle %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Lightbox-->
    <link rel="stylesheet" href="{% static 'vendor/lightbox2/css/lightbox.min.css' %}">
    <!-- Range slider-->
    <link rel="stylesheet" href="{% static 'vendor/nouislider/nouislider.min.css' %}">
    <!-- Bootstrap select-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
    <!-- Owl Carousel-->
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel2/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel2/assets/owl.theme.default.css' %}">
    <!-- Google fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <div class="page-holder">
      {% include 'navbar.html' %}

      {% block content %}

      {% endblock content %}

      {% block payment-gateway %}{% endblock payment-gateway %}
      
      {% include 'footer.html' %}
      {% include 'scripts.html' %}

templates/footer.html
<footer class="bg-dark text-white">
        <div class="container py-4">
          <div class="row py-5">
            <div class="col-md-4 mb-3 mb-md-0">
              <h6 class="text-uppercase mb-3">Customer services</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="#">Help &amp; Contact Us</a></li>
                <li><a class="footer-link" href="#">Returns &amp; Refunds</a></li>
                <li><a class="footer-link" href="#">Online Stores</a></li>
                <li><a class="footer-link" href="#">Terms &amp; Conditions</a></li>
              </ul>
            </div>
            <div class="col-md-4 mb-3 mb-md-0">
              <h6 class="text-uppercase mb-3">Company</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="#">What We Do</a></li>
                <li><a class="footer-link" href="#">Available Services</a></li>
                <li><a class="footer-link" href="#">Latest Posts</a></li>
                <li><a class="footer-link" href="#">FAQs</a></li>
              </ul>
            </div>
            <div class="col-md-4">
              <h6 class="text-uppercase mb-3">Social Media</h6>
              <ul class="list-unstyled mb-0">
                <li>
                  <a class="footer-link" href="https://www.linkedin.com/in/janani-sudhagar-3a074875/" target="_blank">
                    <i class="fab fa-linkedin"></i> LinkedIn
                  </a>
                </li>
                <li>
                  <a class="footer-link" href="https://www.instagram.com/n.jananijanu/?hl=en" target="_blank">
                    <i class="fab fa-instagram"></i> Instagram
                  </a>
                </li>
                <li>
                  <a class="footer-link" href="https://x.com/gsaritha" target="_blank">
                    <i class="fab fa-x-twitter"></i> X (formerly Twitter)
                  </a>
                </li>
                <li>
                  <a class="footer-link" href="https://www.facebook.com/JananiJanuSudhagar" target="_blank">
                    <i class="fab fa-facebook"></i> Facebook
                  </a>
                </li>
              </ul>
            </div>
            
          </div>
          <div class="border-top pt-4" style="border-color: #1d1d1d !important">
            <div class="row">
              <div class="col-lg-6">
                <p class="small text-muted mb-0">&copy; 2025 All rights reserved.</p>
              </div>
              <div class="col-lg-6 text-lg-right">
                <p class="small text-muted mb-0">Website by <a class="text-white reset-anchor" href="https://discord.com/channels/@me" target="_blank">JananiSudhagar</a></p>
              </div>
              
            </div>
          </div>
        </div>
      </footer>

templates/navbar.html
{% load static %}

<!-- Navbar -->
<header class="header bg-white">
  <div class="container px-0 px-lg-3">
    <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0">
      <a class="navbar-brand" href="{% url 'store:home' %}">
        <span class="font-weight-bold text-uppercase text-dark">Jewelry</span>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'store:home' %}">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Categories</a>
            <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
              {% if categories_menu %}
                {% for cat_menu in categories_menu %}
                  <a class="dropdown-item border-0 transition-link" href="{% url 'store:category-products' cat_menu.slug %}">{{ cat_menu.title }}</a>
                {% endfor %}
              {% endif %}
              <hr>
              <a class="dropdown-item border-0 transition-link" href="{% url 'store:categories' %}">All Categories</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:blog-list' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:contact' %}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:shop' %}">Shop</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'store:cart' %}">
                <i class="fas fa-dolly-flatbed mr-1 text-gray"></i>Cart
                <small class="text-gray">({{ cart_items.count }})</small>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="far fa-heart mr-1"></i>
                <small class="text-gray">(0)</small>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-alt mr-1 text-gray"></i>My Account
              </a>
              <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                <a class="dropdown-item border-0 transition-link" href="{% url 'store:profile' %}">Profile</a>
                <a class="dropdown-item border-0 transition-link" href="{% url 'store:cart' %}">Cart</a>
                <a class="dropdown-item border-0 transition-link" href="{% url 'store:orders' %}">Orders</a>
                <a class="dropdown-item border-0 transition-link" href="{% url 'store:password_change' %}">Change Password</a>
                <hr>
                <form action="{% url 'store:logout' %}" method="post" style="display:inline;">
                  {% csrf_token %}
                  <button type="submit" class="dropdown-item border-0 transition-link">Log Out</button>
                </form>
              </div>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'store:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'store:register' %}">Create Account</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div>
</header>

templates/scripts.html
{% load static %}

<!-- JavaScript files-->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'vendor/lightbox2/js/lightbox.min.js' %}"></script>
      <script src="{% static 'vendor/nouislider/nouislider.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2/owl.carousel.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js' %}"></script>
      <script src="{% static 'js/front.js' %}"></script>

      <script>
        var range = document.getElementById('range');
        noUiSlider.create(range, {
            range: {
                'min': 0,
                'max': 2000
            },
            step: 5,
            start: [100, 1000],
            margin: 300,
            connect: true,
            direction: 'ltr',
            orientation: 'horizontal',
            behaviour: 'tap-drag',
            tooltips: true,
            format: {
              to: function ( value ) {
                return '$' + value;
              },
              from: function ( value ) {
                return value.replace('', '');
              }
            }
        });
        
      </script>

      
      <script>
        // ------------------------------------------------------- //
        //   Inject SVG Sprite - 
        //   see more here 
        //   https://css-tricks.com/ajaxing-svg-sprite/
        // ------------------------------------------------------ //
        function injectSvgSprite(path) {
        
            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function(e) {
            var div = document.createElement("div");
            div.className = 'd-none';
            div.innerHTML = ajax.responseText;
            document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }
        // this is set to BootstrapTemple website as you cannot 
        // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
        // while using file:// protocol
        // pls don't forget to change to your domain :)
        injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg'); 
        
      </script>
      <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </div>
  </body>
</html>